language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  # - "3.5-dev"
  - "nightly"

before_install:
    - sudo apt-get install -qq python-scipy

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install .
script: py.test
